export const popularData = [
  {
    place: "Paris",
    durations: "3Days, 4 Nights",
    price: "1650",
    description: "Per person on twin sharing",
    src: "/assets/images/g1.jpg",
  },
  {
    place: "Bangkok",
    durations: "3Days, 4 Nights",
    price: "1850",
    description: "Per person on twin sharing",
    src: "/assets/images/g2.jpg",
  },
  {
    place: "Maldives",
    durations: "3Days, 4 Nights",
    price: "1350",
    description: "Per person on twin sharing",
    src: "/assets/images/g3.jpg",
  },
  {
    place: "Greece",
    durations: "3Days, 4 Nights",
    price: "1750",
    description: "Per person on twin sharing",
    src: "/assets/images/g4.jpg",
  },
  {
    place: "London",
    durations: "3Days, 4 Nights",
    price: "2050",
    description: "Per person on twin sharing",
    src: "/assets/images/g5.jpg",
  },
  {
    place: "Julian Alps",
    durations: "3Days, 4 Nights",
    price: "2150",
    description: "Per person on twin sharing",
    src: "/assets/images/g6.jpg",
  },
  {
    place: "Thailand",
    durations: "3Days, 4 Nights",
    price: "2950",
    description: "Per person on twin sharing",
    src: "/assets/images/g7.jpg",
  },
  {
    place: "Singapore",
    durations: "3Days, 4 Nights",
    price: "2350",
    description: "Per person on twin sharing",
    src: "/assets/images/g8.jpg",
  },
  {
    place: "Singapore",
    durations: "3Days, 4 Nights",
    price: "2550",
    description: "Per person on twin sharing",
    src: "/assets/images/g9.jpg",
  },
  {
    place: "Singapore",
    durations: "3Days, 4 Nights",
    price: "2850",
    description: "Per person on twin sharing",
    src: "/assets/images/g10.jpg",
  },
];
